name: CI

on:
  pull_request:
    branches: [main]
    paths:
      - 'Instaliter/api/**'
      - 'Instaliter/ui/**'

jobs:
  api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        working-directory: Instaliter/api
        run: npm install

      - name: Run build
        working-directory: Instaliter/api
        run: npm run build

      - name: Run linter
        working-directory: Instaliter/api
        run: npm run lint:check

      - name: Run formatter
        working-directory: Instaliter/api
        run: npm run format:check
